const initialFormData = {
    numeroMatricula: "",
    fechaMatricula: "",
    tipoIdentificacionEstudiante: "",
    numeroIdentificacionEstudiante: "",
    primerNombreEstudiante: "",
    segundoNombreEstudiante: "",
    primerApellidoEstudiante: "",
    segundoApellidoEstudiante: "",
    sedeMatricula: "",
    gradoId: "",
    pensionId: "",
    jornada: "",
    institucionEducativaAnterior: "",
    ultimoGradoCursado: "",
    ultimoAnioCursado: "",
    generoEstudianteId: "",
    fechaNacimiento: "",
    edad: "",
    paisNacimiento: "",
    departamentoNacimiento: "",
    municipioNacimiento: "",
    tipoSangre: "",
    epsAfiliado: "",
    ipsAsignada: "",
    arsAfiliado: "",
    nroCarnetSisben: "",
    nivelSisben: "",
    estrato: "",
    primerNombrePadre: "",
    segundoNombrePadre: "",
    primerApellidoPadre: "",
    segundoApellidoPadre: "",

    numeroIdentificacionPadre: "",
    direccionPadre: "",
    barrioPadre: "",
    primerNombreMadre: "",
    segundoNombreMadre: "",
    primerApellidoMadre: "",
    segundoApellidoMadre: "",
    numeroIdentificacionMadre: "",
    numeroCelularPadre: "",
    ocupacionPadre: "",
    correoElectronicoPadre: "",
    autorizacionImagen: "",
    veracidadInformacion: "",
    autorizacionCoctactoEmergencia: "",
    documentacionRecibidaRegistroCivil: "",
    documentacionRecibidaCertificadosEstudios: "",
    documentacionRecibidaFotos: "",
    documentacionRecibidaCertificadoVinculado: "",
    documentacionRecibidaSistemaSocial: "",
    documentacionRecibidaEntidadAseguradora: "",
    documentacionRecibidaSeguroEstudiantil: "",
    documentacionRecibidaCertificadoEstratoSocioeconomico: "",
    documentacionRecibidaPagoSalvo: "",
    documentacionRecibidaRegistroVacunacion: "",
    documentacionRecibidaExamenSerologia: "",
  };
  
  export default initialFormData;
  