const initialFormData = {
    numeroMatricula: "",
    fechaMatricula: "",
    tipoIdentificacionEstudiante: "",
    numeroIdentificacionEstudiante: "",
    primerNombre: "",
    segundoNombre: "",
    primerApellido: "",
    segundoApellido: "",
    sedeMatricula: "",
    grado: "",
    jornada: "",
    institucionEducativaAnterior: "",
    ultimoGradoCursado: "",
    ultimoAnioCursado: "",
    genero: "",
    fechaNacimiento: "",
    edad: "",
    paisNacimiento: "",
    departamentoNacimiento: "",
    municipioNacimiento: "",
  
    tipoSangre: "",
    epsAfiliado: "",
    ipsAsignada: "",
    arsAfiliado: "",
    nroCarnetSisben: "",
    nivelSisben: "",
    estrato: "",
  
    primerNombrePadre: "",
    segundoNombrePadre: "",
    primerApellidoPadre: "",
    segundoApellidoPadre: "",
    tipoIdentificacionPadre: "",
    numeroIdentificacionPadre: "",
    direccionPadre: "",
    barrioPadre: "",
    primerNombreMadre: "",
    segundoNombreMadre: "",
    primerApellidoMadre: "",
    segundoApellidoMadre: "",
    tipoIdentificacionMadre: "",
    numeroIdentificacionMadre: "",
    numeroCelularPadre: "",
    ocupacionPadre: "",
    correoElectronicoPadre: "",
    autorizacionImagen: "",
    veracidadInformacion: "",
    autorizacionCoctactoEmergencia: "",
  };
  
  export default initialFormData;
  