const initialFormData = {
  numeroMatricula: "",
  fechaMatricula: "",
  tipoIdentificacionEstudianteId: "",
  numeroIdentificacionEstudiante: "",
  primerNombreEstudiante: "",
  segundoNombreEstudiante: "",
  primerApellidoEstudiante: "",
  segundoApellidoEstudiante: "",
  sedeMatricula: "",
  gradoId: "",
  pensionId: "",
  jornada: "",
  institucionEducativaAnterior: "",
  ultimoGradoCursado: "",
  ultimoAnioCursado: "",
  generoEstudianteId: "",
  fechaNacimiento: "",
  edad: "",
  paisNacimiento: "",
  departamentoNacimiento: "",
  municipioNacimiento: "",
  tipoSangre: "",
  epsAfiliado: "",
  ipsAsignada: "",
  arsAfiliado: "",
  nroCarnetSisben: "",
  nivelSisben: "",
  estrato: "",
  numeroIdentificacionPadre: "",
  primerNombrePadre: "",
  segundoNombrePadre: "",
  primerApellidoPadre: "",
  segundoApellidoPadre: "",
  //direccionPadre: "",
  //barrioPadre: "",
  //numeroCelularPadre: "",
  //ocupacionPadre: "",
  //correoElectronicoPadre: "",
  primerNombreMadre: "",
  segundoNombreMadre: "",
  primerApellidoMadre: "",
  segundoApellidoMadre: "",
  numeroIdentificacionMadre: "",
  autorizacionImagen: "",
  veracidadInformacion: "",
  autorizacionCoctactoEmergencia: "",
  documentacionRecibidaRegistroCivil: "",
  documentacionRecibidaCertificadosEstudios: "",
  documentacionRecibidaFotos: "",
  documentacionRecibidaCertificadoVinculado: "",
  documentacionRecibidaSistemaSocial: "",
  documentacionRecibidaEntidadAseguradora: "",
  documentacionRecibidaSeguroEstudiantil: "",
  documentacionRecibidaCertificadoEstratoSocioeconomico: "",
  documentacionRecibidaPagoSalvo: "",
  documentacionRecibidaRegistroVacunacion: "",
  documentacionRecibidaExamenSerologia: "",
};

export default initialFormData;

// ✅ Tipo basado en el objeto
export type FormDataType = typeof initialFormData;
