name: Deploy Frontend

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Contabo VPS
        uses: appleboy/ssh-action@master
        env:
          DOCKER_COMPOSE_FILE: "docker-compose-frontend.yml"
          APP_DIR: "/root/apps/colegio/frontend"
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e  # Exit immediately on error
            echo "🔄 Iniciando despliegue del frontend..."
            
            # Configurar swap temporal
            sudo fallocate -l 2G /swapfile
            sudo chmod 600 /swapfile
            sudo mkswap /swapfile
            sudo swapon /swapfile
            
            cd $APP_DIR
            
            # Actualizar código
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            
            # Instalar dependencias si es necesario
            npm install
            
            # Limpiar recursos Docker previos
            docker-compose -f $DOCKER_COMPOSE_FILE down --volumes --remove-orphans
            
            # Construir con límites de recursos
            docker-compose -f $DOCKER_COMPOSE_FILE build --no-cache --memory 2GB
            
            # Iniciar servicios
            docker-compose -f $DOCKER_COMPOSE_FILE up -d --force-recreate
            
            # Limpiar recursos no utilizados
            docker system prune -af --volumes
            sudo swapoff /swapfile && sudo rm /swapfile
            
            echo "✅ Frontend desplegado con éxito"