name: Deploy Frontend

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          DOCKER_COMPOSE_FILE: "docker-compose-frontend.yml"
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            set -e  # Exit immediately on error
            echo "🔄 Iniciando despliegue..."
            
            # Configurar swap temporal
            sudo fallocate -l 2G /swapfile
            sudo chmod 600 /swapfile
            sudo mkswap /swapfile
            sudo swapon /swapfile
            
            cd /home/ubuntu/colegio_alegria_norte
            
            # Clonar repositorio si no existe
            if [ ! -d "front_colegio_alegria" ]; then
              git clone https://github.com/andresmedina840/front_colegio_alegria.git
            fi
            
            # Actualizar código
            cd front_colegio_alegria
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            
            # Limpiar recursos Docker previos
            docker-compose -f $DOCKER_COMPOSE_FILE down --volumes --remove-orphans
            
            # Construir con límites de recursos
            docker-compose -f $DOCKER_COMPOSE_FILE build --no-cache --memory 2GB
            
            # Iniciar servicios
            docker-compose -f $DOCKER_COMPOSE_FILE up -d --force-recreate
            
            # Limpiar recursos no utilizados
            docker system prune -af --volumes
            sudo swapoff /swapfile && sudo rm /swapfile
            
            echo "✅ Despliegue completado con éxito"