name: Deploy Frontend

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Contabo VPS
        uses: appleboy/ssh-action@master
        env:
          APP_DIR: "/root/apps/colegio/front_colegio_alegria"
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            echo "🔄 Iniciando despliegue del frontend..."
            
            cd /root/apps/colegio
            
            # Clonar el repositorio si no existe
            if [ ! -d "front_colegio_alegria" ]; then
              git clone https://github.com/andresmedina840/front_colegio_alegria.git
            fi
            
            cd front_colegio_alegria
            git fetch --all
            LOCAL_COMMIT=$(git rev-parse HEAD)
            REMOTE_COMMIT=$(git rev-parse origin/main)
            
            if [ "$LOCAL_COMMIT" != "$REMOTE_COMMIT" ]; then
              echo "🔄 Se detectaron cambios, actualizando..."
              git reset --hard origin/main
              git pull origin main
              
              # Reconstruir y desplegar solo si hay cambios
              docker-compose -f ../docker-compose.yml build frontend
              docker-compose -f ../docker-compose.yml up -d --no-deps frontend

              # Limpiar recursos innecesarios
              docker system prune -af --volumes
              echo "✅ Frontend desplegado con éxito"
            else
              echo "✅ No hay cambios en el frontend, omitiendo despliegue."
            fi
