name: Deploy Frontend

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Contabo VPS
        uses: appleboy/ssh-action@master
        env:
          APP_DIR: "/root/apps/colegio/front_colegio_alegria"
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            echo "🔄 Iniciando despliegue del frontend..."
            
            # Configurar swap temporal
            sudo fallocate -l 2G /swapfile
            sudo chmod 600 /swapfile
            sudo mkswap /swapfile
            sudo swapon /swapfile
            
            cd /root/apps/colegio
            
            # Clonar/actualizar repositorio
            if [ ! -d "front_colegio_alegria" ]; then
              git clone https://github.com/andresmedina840/front_colegio_alegria.git
            fi
            
            cd front_colegio_alegria
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            
            # Reconstruir y desplegar
            docker-compose -f ../docker-compose.yml build frontend
            docker-compose -f ../docker-compose.yml up -d --no-deps frontend
            
            # Limpieza
            docker system prune -af --volumes
            sudo swapoff /swapfile && sudo rm /swapfile
            echo "✅ Frontend desplegado con éxito"